site_name: Mkdocs Test
copyright: "&copy; 2022 ktokmshr"
nav:
  - Home: index.md
  - About: about.md
  - テスト: test.md
theme:
  language: ja
  name: material
plugins:
  - search:
      lang: ja
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  